# BoumWave Configuration File
# Edit this file to customize your static site generator settings

[paths]
# Folder where your HTML templates are stored
template_folder = "templates"

# Folder where your markdown content files are stored
content_folder = "content"

# Folder where the generated posts will be output
# This will also be used as the URL path segment (e.g., example.com/posts/)
output_folder = "posts"

# HTML template file used to generate posts
# This file should be located in the template_folder
# The markdown content will be rendered and injected into this template
post_template = "post.html"

[site]
# Languages supported by your site
# Examples:
#   Single language: languages = ["en"]
#   Multiple languages: languages = ["fr", "en"]
# Note: You don't need to write every post in every language
languages = ["en"]

# URL of your site (used for canonical links and social media meta tags)
site_url = "https://example.com"

# Path to your site's logo
# This logo will be used for social media meta tags (Open Graph, Twitter Card)
# when sharing articles that don't have their own image
logo_path = "path/to/logo.jpg"
